CREATE ROLE backend_dev LOGIN PASSWORD 'backend_dev_pass';
CREATE ROLE bi_dev LOGIN PASSWORD 'bi_dev_pass';
CREATE ROLE data_engineer LOGIN PASSWORD 'data_engineer_pass';

GRANT USAGE ON SCHEMA SALAM TO backend_dev, bi_dev, data_engineer;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SALAM TO backend_dev;
ALTER DEFAULT PRIVILEGES IN SCHEMA SALAM GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO backend_dev;

GRANT SELECT ON ALL TABLES IN SCHEMA SALAM TO bi_dev;
ALTER DEFAULT PRIVILEGES IN SCHEMA SALAM GRANT SELECT ON TABLES TO bi_dev;

GRANT CREATE ON SCHEMA SALAM TO data_engineer;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA SALAM TO data_engineer;
ALTER DEFAULT PRIVILEGES IN SCHEMA SALAM GRANT ALL PRIVILEGES ON TABLES TO data_engineer;

GRANT CONNECT ON DATABASE postgres TO backend_dev, bi_dev, data_engineer;
